### PR TITLE
- resolve #150: Crash during payload strings truncation

### LINKED ISSUE #150: Crash during payload strings truncation
Fatal Exception: NSRangeException
0  CoreFoundation                 0x1aa01dea4 __exceptionPreprocess
1  libobjc.A.dylib                0x1a91eda50 objc_exception_throw
2  CoreFoundation                 0x1a9f24484 -[NSCache init]
3  Foundation                     0x1aa99e88c -[NSString substringToIndex:]
4  Rollbar                        0x107b454c4 +[RollbarPayloadTruncator truncateString:toTotalBytes:] (RollbarPayloadTruncator.m:267)
5  Rollbar                        0x107b44f24 +[RollbarPayloadTruncator itereateObjectStructure:whileTuncatingStrings:] (RollbarPayloadTruncator.m:157)
6  Rollbar                        0x107b45188 __73+[RollbarPayloadTruncator itereateObjectStructure:whileTuncatingStrings:]_block_invoke_2 (RollbarPayloadTruncator.m:177)
7  CoreFoundation                 0x1a9f03e1c -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]
8  Rollbar                        0x107b45020 +[RollbarPayloadTruncator itereateObjectStructure:whileTuncatingStrings:] (RollbarPayloadTruncator.m:182)
9  Rollbar                        0x107b45188 __73+[RollbarPayloadTruncator itereateObjectStructure:whileTuncatingStrings:]_block_invoke_2 (RollbarPayloadTruncator.m:177)

### PR DESCRIPTION
**Pull request by akornich**
also: unit test build errors

### CODE REVIEW

**Comment by rokob** [comment]
Can you add this test:

```objc
- (void)testTruncateStringToTotalBytesUnicode {
    
    NSString *testString = @"🌍🌍🌍🌍🌍-🌍🌍🌍🌍🌍";
    const int truncationBytesLimit = 10;
    XCTAssertTrue(truncationBytesLimit
                  < [RollbarPayloadTruncator measureTotalEncodingBytes:testString]
                  );
    NSString *truncatedString = [RollbarPayloadTruncator truncateString:testString
                                                           toTotalBytes:truncationBytesLimit];
    XCTAssertTrue([RollbarPayloadTruncator measureTotalEncodingBytes:testString]
                  > [RollbarPayloadTruncator measureTotalEncodingBytes:truncatedString]);
    XCTAssertTrue(truncationBytesLimit
                  >= [RollbarPayloadTruncator measureTotalEncodingBytes:truncatedString]
                  );
    XCTAssertTrue(testString.length > truncatedString.length);
}
```

It crashes with the current code, so it will test that this change fixes things.

**Comment by akornich** [comment]
@rokob , I integrated slightly upgraded test you recommended and completely reworked the truncation implementation based on the best (so far) APIs I found for unicode processing. it provides with more accurate results...

File: Rollbar/RollbarPayloadTruncator.m [hunk 1]
```diff
@@ -250,36 +250,40 @@ +(NSString*)truncateString:(NSString*)inputString
...
+        // we have to have at least the ellipsis as a reasult of a string truncation:
+        return ellipsis;
     }
     
-    return result;
+    NSMutableString *bestFit = [NSMutableString string];
+    NSMutableString *result = [NSMutableString string];
+    [inputString enumerateSubstringsInRange:NSMakeRange(0, inputString.length)
+                                    options:NSStringEnumerationByComposedCharacterSequences | NSStringEnumerationLocalized
+                                 usingBlock:^(NSString *letter, NSRange letterRange, NSRange enclosingLetterRange, BOOL *stop2) {
```
Comment (rokob) [inline Rollbar/RollbarPayloadTruncator.m]: This looks extremely slow. I'm not sure I even need to profile it to say that. Things that are slow:

* Building a string by appending single characters (we are doing this twice here)
* Measuring the size of a string in a given encoding (we are doing this for every character)

All we care about is getting the strings down to something smaller so that we can hopefully shrink the payload a little bit. This is way too much work for something that does not need to be that precise.

Comment (akornich) [reply Rollbar/RollbarPayloadTruncator.m]: agree - it is slow but most accurate so far and probably having lowest risk factor of possible crashes. so, let me try one more time going the way we had it before: less accurate but better performance while limiting risks of possible crashes.

**Comment by rokob** [comment]
Assuming all the tests pass, this looks good to me.

**Comment by akornich** [comment]
all the unit tests pass. including the new one (triplets: initial, truncated, truncated encoding bytes count):
2019-03-05 17:44:09.918978-0800 xctest[35828:3108107] 🌍🌍🌍🌍🌍-🌍🌍🌍🌍🌍
2019-03-05 17:44:09.919140-0800 xctest[35828:3108107] 🌍...
2019-03-05 17:44:09.919268-0800 xctest[35828:3108107] 7
2019-03-05 17:44:09.919381-0800 xctest[35828:3108107] A🌍🌍🌍🌍-🌍🌍🌍🌍🌍
2019-03-05 17:44:09.919491-0800 xctest[35828:3108107] A🌍...
2019-03-05 17:44:09.919597-0800 xctest[35828:3108107] 8
2019-03-05 17:44:09.919723-0800 xctest[35828:3108107] AB🌍🌍🌍-🌍🌍🌍🌍🌍
2019-03-05 17:44:09.919839-0800 xctest[35828:3108107] AB🌍...
2019-03-05 17:44:09.919947-0800 xctest[35828:3108107] 9
2019-03-05 17:44:09.920069-0800 xctest[35828:3108107] ABC🌍🌍-🌍🌍🌍🌍🌍
2019-03-05 17:44:09.920174-0800 xctest[35828:3108107] ABC🌍...
2019-03-05 17:44:09.920262-0800 xctest[35828:3108107] 10
2019-03-05 17:44:09.920394-0800 xctest[35828:3108107] ABCD🌍-🌍🌍🌍🌍🌍
2019-03-05 17:44:09.920515-0800 xctest[35828:3108107] ABCD...
2019-03-05 17:44:09.920606-0800 xctest[35828:3108107] 7
2019-03-05 17:44:09.920768-0800 xctest[35828:3108107] ABCDE-🌍🌍🌍🌍🌍
2019-03-05 17:44:09.920947-0800 xctest[35828:3108107] ABCDE-...
2019-03-05 17:44:09.921124-0800 xctest[35828:3108107] 9
2019-03-05 17:44:09.921359-0800 xctest[35828:3108107] ABCDE-A🌍🌍🌍🌍
2019-03-05 17:44:09.921532-0800 xctest[35828:3108107] ABCDE-A...
2019-03-05 17:44:09.921708-0800 xctest[35828:3108107] 10
2019-03-05 17:44:09.921921-0800 xctest[35828:3108107] ABCDE-AB🌍🌍🌍
2019-03-05 17:44:09.922116-0800 xctest[35828:3108107] ABCDE-A...
2019-03-05 17:44:09.922311-0800 xctest[35828:3108107] 10
2019-03-05 17:44:09.922455-0800 xctest[35828:3108107] ABCDE-ABC🌍🌍
2019-03-05 17:44:09.922611-0800 xctest[35828:3108107] ABCDE-A...
2019-03-05 17:44:09.922755-0800 xctest[35828:3108107] 10
2019-03-05 17:44:09.922999-0800 xctest[35828:3108107] ABCDE-ABCD🌍
2019-03-05 17:44:09.923174-0800 xctest[35828:3108107] ABCDE-A...
2019-03-05 17:44:09.923316-0800 xctest[35828:3108107] 10
2019-03-05 17:44:09.923525-0800 xctest[35828:3108107] 🌍🌍🌍🌍🌍-🌍🌍🌍🌍E
2019-03-05 17:44:09.923638-0800 xctest[35828:3108107] 🌍...
2019-03-05 17:44:09.923817-0800 xctest[35828:3108107] 7
2019-03-05 17:44:09.924031-0800 xctest[35828:3108107] 🌍🌍🌍🌍🌍-🌍🌍🌍DE
2019-03-05 17:44:09.924207-0800 xctest[35828:3108107] 🌍...
2019-03-05 17:44:09.924389-0800 xctest[35828:3108107] 7
2019-03-05 17:44:09.924604-0800 xctest[35828:3108107] 🌍🌍🌍🌍🌍-🌍🌍CDE
2019-03-05 17:44:09.924770-0800 xctest[35828:3108107] 🌍...
2019-03-05 17:44:09.924938-0800 xctest[35828:3108107] 7
2019-03-05 17:44:09.925176-0800 xctest[35828:3108107] 🌍🌍🌍🌍🌍-🌍BCDE
2019-03-05 17:44:09.925313-0800 xctest[35828:3108107] 🌍...
2019-03-05 17:44:09.925528-0800 xctest[35828:3108107] 7
2019-03-05 17:44:09.925737-0800 xctest[35828:3108107] 🌍🌍🌍🌍🌍-ABCDE
2019-03-05 17:44:09.925875-0800 xctest[35828:3108107] 🌍...
2019-03-05 17:44:09.926100-0800 xctest[35828:3108107] 7
2019-03-05 17:44:09.926319-0800 xctest[35828:3108107] 🌍🌍🌍🌍E-ABCDE
2019-03-05 17:44:09.926508-0800 xctest[35828:3108107] 🌍...
2019-03-05 17:44:09.926723-0800 xctest[35828:3108107] 7
2019-03-05 17:44:09.926910-0800 xctest[35828:3108107] 🌍🌍🌍DE-ABCDE
2019-03-05 17:44:09.927069-0800 xctest[35828:3108107] 🌍...
2019-03-05 17:44:09.927277-0800 xctest[35828:3108107] 7
2019-03-05 17:44:09.927510-0800 xctest[35828:3108107] 🌍🌍CDE-ABCDE
2019-03-05 17:44:09.927673-0800 xctest[35828:3108107] 🌍...
2019-03-05 17:44:09.927835-0800 xctest[35828:3108107] 7
2019-03-05 17:44:09.928042-0800 xctest[35828:3108107] 🌍BCDE-ABCDE
2019-03-05 17:44:09.928209-0800 xctest[35828:3108107] 🌍BCD...
2019-03-05 17:44:09.928374-0800 xctest[35828:3108107] 10
2019-03-05 17:44:09.928568-0800 xctest[35828:3108107] ABCDE-ABCDE
2019-03-05 17:44:09.928805-0800 xctest[35828:3108107] ABCDE-A...
2019-03-05 17:44:09.929012-0800 xctest[35828:3108107] 10
2019-03-05 17:44:09.929227-0800 xctest[35828:3108107] אספירין-אספירין
2019-03-05 17:44:09.929431-0800 xctest[35828:3108107] אספ...
2019-03-05 17:44:09.929574-0800 xctest[35828:3108107] 9
2019-03-05 17:44:09.929778-0800 xctest[35828:3108107] Pound123Pound
2019-03-05 17:44:09.929969-0800 xctest[35828:3108107] Pound12...
2019-03-05 17:44:09.930175-0800 xctest[35828:3108107] 10
