### PR TITLE
Release candidate: v1.12.10

### LINKED ISSUE #314: Deprecation warnings break app builds when "treat warnings as errors" is enabled
All of the deprecation warnings recently added to the 1.12.x series generate a lot of warning noise in apps that import `Rollbar.h`. If the project uses the "treat warnings as errors" flag, those warnings also break the build.

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend ...

<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/Rollbar.h"
        ^
/Users/.../Carthage/Build/iOS/Rollbar.framework/Headers/Rollbar.h:42:9: note: in file included from /Users/.../Carthage/Build/iOS/Rollbar.framework/Headers/Rollbar.h:42:
#import <Rollbar/RollbarFacade.h>
        ^
/Users/.../Carthage/Build/iOS/Rollbar.framework/Headers/RollbarFacade.h:5:9: note: in file included from /Users/.../Carthage/Build/iOS/Rollbar.framework/Headers/RollbarFacade.h:5:
#import "RollbarTelemetry.h"
        ^
/Users/.../Carthage/Build/iOS/Rollbar.framework/Headers/RollbarTelemetry.h:7:9: note: in file included from /Users/.../Carthage/Build/iOS/Rollbar.framework/Headers/RollbarTelemetry.h:7:
#import "RollbarTelemetryEvent.h"
        ^
/Users/.../Carthage/Build/iOS/Rollbar.framework/Headers/RollbarTelemetryEvent.h:20:36: error: 'DataTransferObject' is deprecated: In v2, use RollbarDTO instead.
@interface RollbarTelemetryEvent : DataTransferObject
                                   ^
/Users/.../Carthage/Build/iOS/Rollbar.framework/Headers/DataTransferObject.h:14:1: note: 'DataTransferObject' has been explicitly marked deprecated here
DEPRECATED_MSG_ATTRIBUTE("In v2, use RollbarDTO instead.")
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.6.sdk/usr/include/AvailabilityMacros.h:182:64: note: expanded from macro 'DEPRECATED_MSG_ATTRIBUTE'
            #define DEPRECATED_MSG_ATTRIBUTE(s) __attribute__((deprecated(s)))
                                                               ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/Rollbar.h"
        ^
/Users/.../Carthage/Build/iOS/Rollbar.framework/Headers/Rollbar.h:42:9: note: in file included from /Users/.../Carthage/Build/iOS/Rollbar.framework/Headers/Rollbar.h:42:
#import <Rollbar/RollbarFacade.h>
        ^
/Users/.../Carthage/Build/iOS/Rollbar.framework/Headers/RollbarFacade.h:5:9: note: in file included from /Users/.../Carthage/Build/iOS/Rollbar.framework/Headers/RollbarFacade.h:5:
#import "RollbarTelemetry.h"
        ^
/Users/.../Carthage/Build/iOS/Rollbar.framework/Headers/RollbarTelemetry.h:8:9: note: in file included from /Users/.../Carthage/Build/iOS/Rollbar.framework/Headers/RollbarTelemetry.h:8:
#import "RollbarTelemetryBody.h"
        ^
/Users/.../Carthage/Build/iOS/Rollbar.framework/Headers/RollbarTelemetryBody.h:15:35: error: 'DataTransferObject' is deprecated: In v2, use RollbarDTO instead.
@interface RollbarTelemetryBody : DataTransferObject
                                  ^
/Users/.../Carthage/Build/iOS/Rollbar.framework/Headers/DataTransferObject.h:14:1: note: 'DataTransferObject' has been explicitly marked deprecated here
DEPRECATED_MSG_ATTRIBUTE("In v2, use RollbarDTO instead.")
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.6.sdk/usr/include/AvailabilityMacros.h:182:64: note: expanded from macro 'DEPRECATED_MSG_ATTRIBUTE'
            #define DEPRECATED_MSG_ATTRIBUTE(s) __attribute__((deprecated(s)))
```

(trimmed for brevity)

### PR DESCRIPTION
**Pull request by akornich**
## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix #314
### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

File: Rollbar/Abstraction_Common/JSONSupport.h [hunk 1]
```diff
@@ -11,7 +11,7 @@
 NS_ASSUME_NONNULL_BEGIN
 
 /// JSON de/serialization protocol
-DEPRECATED_MSG_ATTRIBUTE("In v2, use RollbarJSONSupport instead.")
+//DEPRECATED_MSG_ATTRIBUTE("In v2, use RollbarJSONSupport instead.")
```
Comment (mrunalk) [inline Rollbar/Abstraction_Common/JSONSupport.h:14]: Question: Why are we commenting the deprecated message here and many other places? Will these comments be removed in future?

**Review by mrunalk — APPROVED** [review]
LGTM with a question.

File: Rollbar/Abstraction_Common/JSONSupport.h (hunk 1 above)
Comment (akornich) [reply Rollbar/Abstraction_Common/JSONSupport.h:14]: @mrunalk, the plan is to uncomment out these back when the official v2 is released and have sort of final v1 release we these deprecation warnings that would help to guide the SDK users during v1 to v2 transition.
